server:
  port: 8070

pubsub:
  subscription_id: ${SUBSCRIPTION_ID:demo_topic-sub}
  projectId: my-demo-project-341408


encryption:
  key_ring: my-asymmetric-signing-key1
  key_id: my-new-key-id
  location_id: global